### ISSUE TITLE
TypeError: REGEX_DATABASE_URL.exec is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by denisoster** [sastraxi/pgsh#25]
If I try to connect via `url` or `split` mode getting an error
`TypeError: REGEX_DATABASE_URL.exec is not a function or its return value is not iterable`

**Comment by sastraxi** [comment]
Can you share `pgsh --version`, your .pgshrc, and the relevant (obfuscated) portion of your .env?

**Comment by denisoster** [comment]
@sastraxi 
>pgsh --version

0.6.1

[.env and .pgshrc](https://gist.github.com/denisoster/de6bca0da3588db5957d4576846663dc)

**Comment by sastraxi** [comment]
Thanks, Denis. Ill

**Comment by sastraxi** [comment]
@denisoster can you try `pgsh@0.6.2` and see if it solves your issue?

I wasn't able to reproduce your exact error, but I think it's failing due to the hyphen. The new version fully supports hyphenated database names (along with many other special characters).

**Comment by denisoster** [comment]
@sastraxi 
problem persisted
`{
  "mode": "url",
  "vars": {
    "url": "DATABASE_URL"
  }`

`DATABASE_URL=postgres://sandbox@localhost:5432/sandbox_db`

`pgsh -a`
`postgres: REGEX_DATABASE_URL.exec is not a function or its return value is not iterable`

**Comment by sastraxi** [comment]
@denisoster OK, I can reproduce that! The issue is that you don't have a `password` in your connection string. You can get up and running right now by adding your password after your username, like:

`DATABASE_URL=postgres://sandbox:<password>@localhost:5432/sandbox_db`

I'm treating this as an enhancement and tracking in #29; should have a fix out soon.

**Comment by denisoster** [comment]
@sastraxi  I do not have a password to the database. Then how should I be?

**Comment by sastraxi** [comment]
@denisoster I'm re-writing the logic to allow this; I made a lot of assumptions about connection strings and what psql / pg requires that turned out to not be true. Should be fixed later today!

**Comment by sastraxi** [comment]
@denisoster fixed in `0.7.1` and later; try it out and let me know if things are working!

**Comment by sastraxi** [comment]
@denisoster sorry for the spam, but could you comment on #31 if you have a `DATABASE_URL` in your OS environment? Was just doing some thinking and maybe I couldn't repro at first because the `DATABASE_URL` in `.env` was being skipped (see [this](https://www.npmjs.com/package/dotenv#what-happens-to-environment-variables-that-were-already-set) for more details)

**Comment by denisoster** [comment]
@sastraxi 
Everything is working. 
Thank you for fixing it quickly.
